In [18]:
import torch

x = torch.tensor([3.0]) #0维的张量通过按元素运算结果也为0维
y = torch.tensor([2.0])
x + y,x * y,x / y,x ** y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

In [3]:
x = torch.arange(4) #将由标量值组成的列表称为向量，构成一维张量
x

tensor([0, 1, 2, 3])

In [4]:
x[3] #通过索引访问元素

tensor(3)

In [9]:
A = torch.arange(20).reshape(5,4) #将矩阵视为二维张量
#定义一个矩阵，元素值是0-19的序列，矩阵形状是五行四列
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [10]:
A.T  #直接实现转置

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [11]:
A == A.T #验证转置后的矩阵，该逻辑是逐元素比较，而 4*5 与 5*4 不匹配，而报错

RuntimeError: The size of tensor a (4) must match the size of tensor b (5) at non-singleton dimension 1

In [17]:
B = torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
B #定义一个对称矩阵，验证转置矩阵的基本性质

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [18]:
B.T
B == B.T #验证性质,对称矩阵的转置等于它本身

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [19]:
X = torch.arange(24).reshape(2,3,4)
X #三维的张量由 n 个批量的二维矩阵构成，批量即是第三维度

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [29]:
A = torch.arange(20,dtype = torch.float32).reshape(5,4)
B = A.clone() #重新分配内存的操作
A, A + B
#给定相同形状的两个张量，进行按元素的二元运算的结果都是相同形状的张量

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [7]:
A * B #这里的乘法是按元素的乘法，被称为哈达玛积

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [8]:
a = 2
X = torch.arange(24).reshape(2,3,4)
a + X,(a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [36]:
x = torch.arange(4,dtype = torch.float32) #sum()函数求元素和
x,x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [10]:
A.shape,A.sum()

(torch.Size([5, 4]), tensor(190.))

In [11]:
A_sum_axis0 = A.sum(axis=0)b #每列求和，压缩成一行的一维向量
A_sum_axis0,A_sum_axis0.shape

(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [14]:
A.sum(axis=[0,1]) #全求和,等同于A.sum()

tensor(190.)

In [25]:
A.mean(), A.sum() / A.numel() #numel()的函数的作用是统计张量的元素个数

(tensor(9.5000), tensor(9.5000))

In [26]:
A.mean(axis = 0),A.sum(axis = 0)/A.shape[0] ,#每列的平均值，每列和 / 列数 

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

In [31]:
sum_A = A.sum(axis = 1,keepdims=True) #维度虽然变 1 了，但结构还在，方便后续做加减乘除。保留了被压缩为0的结构
sum_A,A.shape

(tensor([[ 6.],
         [22.],
         [38.],
         [54.],
         [70.]]),
 torch.Size([5, 4]))

In [32]:
A.sum(axis = 1),A.shape

(tensor([ 6., 22., 38., 54., 70.]), torch.Size([5, 4]))

In [33]:
A / sum_A #各个元素都除以总值

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [34]:
A.cumsum(axis = 0) #沿着第 0 维（纵向/行方向）进行“累积求和”

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [37]:
#求点积，相同位置的按元素的乘积的和
y = torch.ones(4, dtype=torch.float32)
x,y,torch.dot(x,y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [38]:
torch.sum(x * y) #点积公式

tensor(6.)

In [39]:
A.shape,x.shape,torch.mv(A,x) #矩阵与向量乘法

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

In [40]:
B = torch.ones(4,3) #矩阵乘法公式
torch.mm(A,B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

In [41]:
u = torch.tensor([3.0,-4.0])
torch.norm(u)  #L2范数是向量元素平方和的平方根

tensor(5.)

In [42]:
torch.abs(u).sum() #L1范数是向量元素绝对值的和

tensor(7.)