In [1]:
import torch

x = torch.arange(4.0)
x #定义一个向量

tensor([0., 1., 2., 3.])

In [2]:
#储存梯度
x.requires_grad_(True) #等价于 “x = torch.arange(4.0,requires_grad=True)”
x.grad #默认值是none

In [3]:
y = 2 * torch.dot(x,x) #y = 2x **2
y

tensor(28., grad_fn=<MulBackward0>)

In [4]:
y.backward() #使用反向传播函数自动计算y关于x每个分量的梯度
x.grad

tensor([ 0.,  4.,  8., 12.])

In [5]:
x.grad == 4 * x

tensor([True, True, True, True])

In [6]:
#计算x的另一个函数
x.grad.zero_() #因为默认情况下pytorch会积累梯度，需要清空之前的梯度值
y = x.sum() #求向量各元素和
y.backward() #反向传播
x.grad

tensor([1., 1., 1., 1.])

In [8]:
x.grad.zero_()
y = x * x #y,backward(torch.ones(len(x)))
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [9]:
x.grad.zero_()
y = x * x
u = y.detach()  #detach的作用很特殊，把 y 的值拿出来，复制一份给 u，但切断 u 和 x 的联系
z = u * x #在pytorch里相当于z=C×x，实际上是 z=x*x**2

z.sum().backward() #因为(C⋅x) = C，求导后等于u = x**2
x.grad == u #验证储存的梯度是否等于u，确实把u当成了常数c，没有对它求导

tensor([True, True, True, True])

In [10]:
x.grad.zero_()
y.sum().backward() #对y = x*x 求导
x.grad == 2 * x #验证 y = x*x 》 2x

tensor([True, True, True, True])

In [12]:
def f(a):
    b = a * 2 #只要 b 的范数小于 1000，就一直乘 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0: #判断：根据 b 的和是否大于 0，走不同的分支
        c = b
    else:
        c = 100 * b
    return c
#创建一个随机的标量 a，并要求记录梯度
a = torch.randn(size=(),requires_grad=True)
d = f(a)
d.backward()

a.grad == d / a #验证a的梯度

tensor(True)